import React, { useState } from 'react';
import { Alert, ScrollView, StyleSheet, TextInput, Pressable as TouchableOpacity, View } from 'react-native';
import ScreenHeader from '../components/ScreenHeader';
import AppText from '../components/AppText';
import PrimaryButton from '../components/PrimaryButton';
import { useApp } from '../context/AppContext';
import { colors, radius, spacing } from '../theme';

const categories=['hotels','food','transport','activities','misc'];
export default function AddExpenseScreen({navigation,route}){
  const {currentTrip,addExpense,updateExpense}=useApp();const existing=route.params?.expense;
  const [category,setCategory]=useState(existing?.category||'food');const [amount,setAmount]=useState(existing?String(existing.amount):'');const [note,setNote]=useState(existing?.note||'');const [day,setDay]=useState(existing?.day?String(existing.day):'');const [loading,setLoading]=useState(false);
  async function save(){const value=Number(amount);if(!Number.isFinite(value)||value<=0)return Alert.alert('Invalid amount','Enter a positive expense amount.');setLoading(true);try{const body={category,amount:value,note,day:day?Number(day):undefined};if(existing)await updateExpense(existing._id,body);else await addExpense(body);navigation.goBack();}catch(error){Alert.alert('Could not save expense',error.message);}finally{setLoading(false);}}
  return <View style={styles.page}><ScreenHeader title={existing?'Edit expense':'Add expense'} subtitle={currentTrip?.destination||'Current trip'} onBack={()=>navigation.goBack()}/><ScrollView contentContainerStyle={styles.content}><AppText variant="caption" color={colors.muted}>CATEGORY</AppText><View style={styles.wrap}>{categories.map(item=><TouchableOpacity key={item} onPress={()=>setCategory(item)} style={[styles.chip,category===item&&styles.on]}><AppText variant="label" color={category===item?colors.white:colors.ink}>{item.toUpperCase()}</AppText></TouchableOpacity>)}</View><AppText variant="caption" color={colors.muted}>AMOUNT (PKR)</AppText><TextInput style={styles.input} value={amount} onChangeText={setAmount} keyboardType="number-pad" placeholder="2500"/><AppText variant="caption" color={colors.muted}>TRIP DAY (OPTIONAL)</AppText><TextInput style={styles.input} value={day} onChangeText={setDay} keyboardType="number-pad" placeholder={`1-${currentTrip?.days||1}`}/><AppText variant="caption" color={colors.muted}>NOTE</AppText><TextInput style={[styles.input,{height:90,textAlignVertical:'top',paddingTop:12}]} value={note} onChangeText={setNote} multiline placeholder="Lunch, taxi, entry tickets..."/><PrimaryButton title="SAVE EXPENSE" onPress={save} loading={loading}/></ScrollView></View>;
}
const styles=StyleSheet.create({page:{flex:1,backgroundColor:colors.cream},content:{padding:spacing.lg,gap:spacing.sm},wrap:{flexDirection:'row',flexWrap:'wrap',gap:7,marginBottom:10},chip:{paddingHorizontal:11,paddingVertical:8,borderRadius:radius.pill,backgroundColor:colors.paper,borderWidth:1,borderColor:colors.line},on:{backgroundColor:colors.forest,borderColor:colors.forest},input:{minHeight:50,borderWidth:1,borderColor:colors.line,borderRadius:radius.md,backgroundColor:colors.paper,paddingHorizontal:14,color:colors.ink,marginBottom:8}});
