import React, { useState } from 'react';
import { Alert, ScrollView, StyleSheet, TextInput, Pressable as TouchableOpacity, View } from 'react-native';
import ScreenHeader from '../components/ScreenHeader';
import AppText from '../components/AppText';
import AppIcon from '../components/AppIcon';
import PrimaryButton from '../components/PrimaryButton';
import { useApp } from '../context/AppContext';
import { colors, radius, shadowSoft, spacing } from '../theme';

export default function EditItineraryScreen({ navigation }) {
  const { currentTrip, saveItinerary } = useApp();
  const [itinerary, setItinerary] = useState(JSON.parse(JSON.stringify(currentTrip?.itinerary || [])));
  const [dayIndex, setDayIndex] = useState(0);
  const [loading, setLoading] = useState(false);
  const activities = itinerary[dayIndex]?.activities || [];
  function change(index, key, value) { setItinerary((old) => old.map((day, d) => d !== dayIndex ? day : ({ ...day, activities: day.activities.map((item, i) => i === index ? { ...item, [key]: key === 'estimatedCost' ? Number(value) || 0 : value } : item) }))); }
  function remove(index) { if (activities.length === 1) return Alert.alert('One activity required', 'Each day must keep at least one activity.'); setItinerary((old) => old.map((day,d) => d !== dayIndex ? day : ({...day,activities:day.activities.filter((_,i)=>i!==index)}))); }
  function move(index, offset) { const target=index+offset;if(target<0||target>=activities.length)return;setItinerary((old)=>old.map((day,d)=>{if(d!==dayIndex)return day;const next=[...day.activities];[next[index],next[target]]=[next[target],next[index]];return {...day,activities:next};})); }
  function add() { setItinerary((old)=>old.map((day,d)=>d!==dayIndex?day:{...day,activities:[...day.activities,{time:'Flexible',place:'New activity',type:'culture',description:'Add details for this stop.',estimatedCost:0}]})); }
  async function save(){setLoading(true);try{await saveItinerary(itinerary);navigation.goBack();}catch(error){Alert.alert('Could not save',error.message);}finally{setLoading(false);}}
  return <View style={styles.page}><ScreenHeader title="Edit itinerary" subtitle="Changes recalculate routes and budget" onBack={()=>navigation.goBack()} /><View style={styles.tabs}><ScrollView horizontal>{itinerary.map((day,index)=><TouchableOpacity key={day.day} onPress={()=>setDayIndex(index)} style={[styles.tab,index===dayIndex&&styles.tabOn]}><AppText variant="label" color={index===dayIndex?colors.white:colors.ink}>Day {day.day}</AppText></TouchableOpacity>)}</ScrollView></View><ScrollView contentContainerStyle={styles.content}>{activities.map((item,index)=><View key={`${index}-${item.place}`} style={styles.card}><View style={styles.tools}><TouchableOpacity onPress={()=>move(index,-1)}><AppIcon name="arrow-up" size={20} color={colors.forest}/></TouchableOpacity><TouchableOpacity onPress={()=>move(index,1)}><AppIcon name="arrow-down" size={20} color={colors.forest}/></TouchableOpacity><TouchableOpacity onPress={()=>remove(index)}><AppIcon name="trash-outline" size={20} color={colors.red}/></TouchableOpacity></View><TextInput style={styles.input} value={item.time} onChangeText={(v)=>change(index,'time',v)} placeholder="Time"/><TextInput style={styles.input} value={item.place} onChangeText={(v)=>change(index,'place',v)} placeholder="Place"/><TextInput style={[styles.input,styles.multiline]} value={item.description} onChangeText={(v)=>change(index,'description',v)} multiline placeholder="Description"/><TextInput style={styles.input} value={String(item.estimatedCost)} onChangeText={(v)=>change(index,'estimatedCost',v)} keyboardType="number-pad" placeholder="Cost in PKR"/></View>)}<TouchableOpacity style={styles.add} onPress={add}><AppIcon name="add-circle-outline" color={colors.forest}/><AppText variant="label" color={colors.forest}>ADD ACTIVITY</AppText></TouchableOpacity><PrimaryButton title="SAVE ITINERARY" onPress={save} loading={loading}/></ScrollView></View>;
}
const styles=StyleSheet.create({page:{flex:1,backgroundColor:colors.cream},tabs:{backgroundColor:colors.paper,padding:10},tab:{paddingHorizontal:14,paddingVertical:9,borderRadius:radius.pill,marginRight:7,backgroundColor:colors.cream},tabOn:{backgroundColor:colors.forest},content:{padding:spacing.lg,paddingBottom:40},card:{...shadowSoft,backgroundColor:colors.paper,borderRadius:radius.lg,padding:spacing.md,marginBottom:spacing.md},tools:{flexDirection:'row',justifyContent:'flex-end',gap:20,marginBottom:8},input:{minHeight:44,borderWidth:1,borderColor:colors.line,borderRadius:radius.sm,paddingHorizontal:12,marginTop:7,color:colors.ink},multiline:{minHeight:70,paddingTop:10,textAlignVertical:'top'},add:{minHeight:48,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:7,borderWidth:1,borderColor:colors.forest,borderRadius:radius.md,marginBottom:12}});
